name: Deploy app

on:
  push:
    branches:
      - 1-setup-project-template
jobs:
  testing:
    uses: ./.github/workflows/test-base.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
  deploy:
    runs-on: self-hosted
    needs: testing
    steps:
      - run: echo 'It works'
