name: Deploy app

on:
  push:
    branches:
      - 1-setup-project-template
env:
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  AWS_ACCESS_TOKEN: ${{ secrets.AWS_ACCESS_TOKEN}}
jobs:
jobs:
  testing:
    uses: ./.github/workflows/test-base.yml
  build:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./scripts/build.sh
      - run: ./scripts/build.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
