name: Deploy app

on: push
env:
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  AWS_ACCESS_TOKEN: ${{ secrets.AWS_ACCESS_TOKEN}}
jobs:
  testing:
    uses: ./.github/workflows/test-base.yml
